### ISSUE TITLE
Memoization bug?

### ISSUE THREAD

**Issue by olivierverdier** [henriksu/pybs#22]
Calling `split` prevents `modifiedEquation` from working. Quite strange, but completely reproducible, see the test added in 978f9248b82f12ecc928c315668c1e70da11a973

**Comment by henriksu** [comment]
I don't know exactly what happens, but the connection is as follows:

modifiedEquation uses the Lie derivative and the Lie derivative uses split. However, to stop modifiedEquation from embarking on an infinit recusion, the last pair returned by split must be omitted. A human sees that the problematic recusive call can be dropped because its result is multiplied by zero (a result of b(Ø)=0 for all modified equations. I solved it by passing truncate=True from modifiedEquation to lieDerivative, which passes it on to split(). Split har truncate=False as a default parameter.

Since only _split() and not split() is memoized, I cannot immediately see why this should cause a problem. But at least it it expalins how modifiedEquation and split are connected.

**Comment by henriksu** [comment]
DISREGARD MY LAST POST.
I think this is what happens:
First time split is called, the object returned from _split(t) is (correctly) altered by an inplace add of the pair (Ø, t). When split(t, truncate=True) is called, the same object is returned, but it is not the right object since it was changed by the inplace add in the first call to split(). 

The moral of the story being: Don't memoize if the returned object is mutable.

**Comment by olivierverdier** [comment]
Well done! One possible solution is to write the modifiedEquation function differently, basically by encapsulating it in a class (which was already `memoize` did) which is tailored just for that need. I think it would be better this way because recursion is often ineffective in Python (even with memoization).
